import { collections, products } from "../../../../drizzle/schema";
export declare function getCollections(): Promise<{
    id: number;
    slug: string;
    nameTr: string;
    nameEn: string;
    descriptionTr: string;
    descriptionEn: string;
    imageUrl: string;
    displayOrder: number;
    createdAt: Date;
    updatedAt: Date;
}[]>;
export declare function getCollectionBySlug(slug: string): Promise<{
    id: number;
    slug: string;
    nameTr: string;
    nameEn: string;
    descriptionTr: string;
    descriptionEn: string;
    imageUrl: string;
    displayOrder: number;
    createdAt: Date;
    updatedAt: Date;
}>;
export declare function createCollection(data: typeof collections.$inferInsert): Promise<number>;
export declare function updateCollection(id: number, data: Partial<typeof collections.$inferInsert>): Promise<void>;
export declare function deleteCollection(id: number): Promise<void>;
export declare function getProducts(options?: {
    collectionId?: number;
    collectionSlug?: string;
    featured?: boolean;
}): Promise<{
    id: number;
    collectionId: number;
    slug: string;
    nameTr: string;
    nameEn: string;
    descriptionTr: string;
    descriptionEn: string;
    compositionTr: string;
    compositionEn: string;
    storyTr: string;
    storyEn: string;
    price: number;
    stock: number;
    imageUrl: string;
    featured: number;
    createdAt: Date;
    updatedAt: Date;
}[]>;
export declare function getFeaturedProducts(limit?: number): Promise<{
    id: number;
    collectionId: number;
    slug: string;
    nameTr: string;
    nameEn: string;
    descriptionTr: string;
    descriptionEn: string;
    compositionTr: string;
    compositionEn: string;
    storyTr: string;
    storyEn: string;
    price: number;
    stock: number;
    imageUrl: string;
    featured: number;
    createdAt: Date;
    updatedAt: Date;
}[]>;
export declare function getProductBySlug(slug: string): Promise<{
    id: number;
    collectionId: number;
    slug: string;
    nameTr: string;
    nameEn: string;
    descriptionTr: string;
    descriptionEn: string;
    compositionTr: string;
    compositionEn: string;
    storyTr: string;
    storyEn: string;
    price: number;
    stock: number;
    imageUrl: string;
    featured: number;
    createdAt: Date;
    updatedAt: Date;
}>;
export declare function getProductById(id: number): Promise<{
    id: number;
    collectionId: number;
    slug: string;
    nameTr: string;
    nameEn: string;
    descriptionTr: string;
    descriptionEn: string;
    compositionTr: string;
    compositionEn: string;
    storyTr: string;
    storyEn: string;
    price: number;
    stock: number;
    imageUrl: string;
    featured: number;
    createdAt: Date;
    updatedAt: Date;
}>;
export declare function createProduct(data: typeof products.$inferInsert): Promise<number>;
export declare function updateProduct(id: number, data: Partial<typeof products.$inferInsert>): Promise<void>;
export declare function deleteProduct(id: number): Promise<void>;
export declare function replaceProductImages(productId: number, images: {
    imageUrl: string;
    altText?: string;
    displayOrder?: number;
}[]): Promise<void>;
export declare function getProductImages(productId: number): Promise<{
    id: number;
    productId: number;
    imageUrl: string;
    altText: string;
    displayOrder: number;
    createdAt: Date;
}[]>;
