"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var authRoutes_1 = require("./authRoutes");
var catalogRoutes_1 = require("./catalogRoutes");
var cartRoutes_1 = require("./cartRoutes");
var orderRoutes_1 = require("./orderRoutes");
var marketingRoutes_1 = require("./marketingRoutes");
var settingsRoutes_1 = require("./settingsRoutes");
var checkoutRoutes_1 = require("./checkoutRoutes");
var router = (0, express_1.Router)();
router.use("/auth", authRoutes_1.default);
router.use("/catalog", catalogRoutes_1.default);
router.use("/cart", cartRoutes_1.default);
router.use("/orders", orderRoutes_1.default);
router.use("/marketing", marketingRoutes_1.default);
router.use("/settings", settingsRoutes_1.default);
router.use("/checkout", checkoutRoutes_1.default);
exports.default = router;
